const PROVERBS_DATA = [
    "Ăn quả nhớ kẻ trồng cây",
    "Công cha như núi Thái Sơn, Nghĩa mẹ như nước trong nguồn chảy ra",
    "Anh em như thể tay chân, Rách lành đùm bọc dở hay đỡ đần",
    "Chị ngã em nâng",
    "Bầu ơi thương lấy bí cùng, Tuy rằng khác giống nhưng chung một giàn",
    "Uống nước nhớ nguồn",
    "Có nuôi con mới biết lòng cha mẹ",
    "Lá lành đùm lá rách",
    "Một giọt máu đào hơn ao nước lã",
    "Con hơn cha là nhà có phúc",
    "Cá không ăn muối cá ươn, con cãi cha mẹ trăm đường con hư",
    "Anh em thuận hòa là nhà có phúc",
    "Ân cha nặng lắm cha ơi! Nghĩa mẹ bằng trời chín tháng cưu mang",
    "Có công mài sắt có ngày nên kim",
    "Đi một ngày đàng học một sàng khôn",
    "Học thầy không tày học bạn",
    "Tiên học lễ hậu học văn",
    "Lửa thử vàng gian nan thử sức",
    "Học đi đôi với hành",
    "Có chí thì nên",
    "Muốn biết phải hỏi, muốn giỏi phải học",
    "Không thầy đố mày làm nên",
    "Gần mực thì đen gần đèn thì sáng",
    "Đói cho sạch rách cho thơm",
    "Một lần bất tín vạn lần bất tin",
    "Sông sâu còn có kẻ dò, lòng người nham hiểm ai đo cho cùng",
    "Phép vua thua lệ làng",
    "Tốt gỗ hơn tốt nước sơn",
    "Giấy rách phải giữ lấy lề",
    "Một miếng khi đói bằng một gói khi no",
    "Cây ngay không sợ chết đứng",
    "Muốn lành nghề chớ ngại học hỏi",
    "Chuồn chuồn bay thấp thì mưa, bay cao thì nắng bay vừa thì râm",
    "Kiến tha lâu đầy tổ",
    "Tấc đất tấc vàng",
    "Đêm tháng Năm chưa nằm đã sáng, ngày tháng Mười chưa cười đã tối",
    "Nhất nước, nhì phân, tam cần, tứ giống",
    "Lúa chiêm lấp ló đầu bờ, Hễ nghe tiếng sấm phất cờ mà lên",
    "Mau sao thì nắng, vắng sao thì mưa",
    "Ráng mỡ gà, có nhà thì giữ",
    "Ăn kỹ no lâu, cày sâu tốt lúa",
    "Khoai đất lạ, mạ đất quen",
    "Chậm như rùa",
    "Nhanh như sóc",
    "Khỏe như voi",
    "Hiền như đất",
    "Thẳng như ruột ngựa",
    "Đầu voi đuôi chuột",
    "Nuôi ong tay áo",
    "Cưỡi ngựa xem hoa",
    "Môi hở răng lạnh",
    "Tôn sư trọng đạo",
    "Của ít lòng nhiều",
    "Vạn sự khởi đầu nan",
    "Một điều nhịn là chín điều lành",
    "Thuận vợ thuận chồng, tát biển Đông cũng cạn",
    "Ngựa non háu đá",
    "Lo bạc râu, rầu bạc tóc",
    "Nói thì dễ, làm thì khó",
    "Tre non dễ uốn",
    "Vô hoạn nạn, bất anh hùng",
    "Ớt nào là ớt chẳng cay, Gái nào là chẳng hay ghen chồng",
    "No ba ngày tết, đói ba tháng hè",
    "Quân vô tướng như hổ vô đầu",
    "Mấy đời bánh đúc có xương",
    "Cháy nhà mới ra mặt chuột",
    "Đàn gẩy tai trâu",
    "Chó treo, mèo đậy",
    "Lên voi xuống chó",
    "Giận cá chém thớt",
    "Cơm áo gạo tiền",
    "Châu chấu đá xe",
    "Kẻ cắp gặp bà già",
    "Đố ai lặn xuống vực sâu, Mà đo miệng cá, uốn câu cho vừa",
    "Đố ai lượm đá quăng trời, Đan gầu tát biển, ghẹo người trong trăng",
    "Đan phên chắn gió, giết voi xem giò",
    "Đố ai tát bể Đông Khê, Tát sông Bồ Đề, nhổ mạ cấy chiêm"
];
